// Copyright (C) 2019 Michael J. Fromberger. All Rights Reserved.

// Package keypb defines a storage format for an encrypted key file.  The keys
// in a key file are symmetrically encrypted based on a passphrase. The
// implementation of this package is generated by the protocol buffer compiler.
package keypb

//go:generate protoc --go_out=. key.proto
