// Copyright (C) 2019 Michael J. Fromberger. All Rights Reserved.

// Package keypb defines a storage format for an encrypted key file.  A key
// file is symmetrically encrypted based on a passphrase. The implementation of
// this package is generated by the protocol buffer compiler.
package keypb

//go:generate protoc --go_out=. key.proto
