// Code generated by protoc-gen-go. DO NOT EDIT.
// source: key.proto

package keypb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Keyfile is the storage format for a key file. The keys in a file are
// encrypted with AES-256 using a key derived from a passphrase using scrypt.
type Keyfile struct {
	// The keys i
	KeySalt              []byte         `protobuf:"bytes,1,opt,name=key_salt,json=keySalt,proto3" json:"key_salt,omitempty"`
	Keys                 []*Keyfile_Key `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Keyfile) Reset()         { *m = Keyfile{} }
func (m *Keyfile) String() string { return proto.CompactTextString(m) }
func (*Keyfile) ProtoMessage()    {}
func (*Keyfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2accf5df6005b7d4, []int{0}
}

func (m *Keyfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keyfile.Unmarshal(m, b)
}
func (m *Keyfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keyfile.Marshal(b, m, deterministic)
}
func (m *Keyfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keyfile.Merge(m, src)
}
func (m *Keyfile) XXX_Size() int {
	return xxx_messageInfo_Keyfile.Size(m)
}
func (m *Keyfile) XXX_DiscardUnknown() {
	xxx_messageInfo_Keyfile.DiscardUnknown(m)
}

var xxx_messageInfo_Keyfile proto.InternalMessageInfo

func (m *Keyfile) GetKeySalt() []byte {
	if m != nil {
		return m.KeySalt
	}
	return nil
}

func (m *Keyfile) GetKeys() []*Keyfile_Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

// A Key is stored as a wire-format Secret which has been compressed and
// encrypted in CTR mode. Each key has a slug that can be used to choose
// which key to decrypt.
type Keyfile_Key struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Init                 []byte   `protobuf:"bytes,3,opt,name=init,proto3" json:"init,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keyfile_Key) Reset()         { *m = Keyfile_Key{} }
func (m *Keyfile_Key) String() string { return proto.CompactTextString(m) }
func (*Keyfile_Key) ProtoMessage()    {}
func (*Keyfile_Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_2accf5df6005b7d4, []int{0, 0}
}

func (m *Keyfile_Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keyfile_Key.Unmarshal(m, b)
}
func (m *Keyfile_Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keyfile_Key.Marshal(b, m, deterministic)
}
func (m *Keyfile_Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keyfile_Key.Merge(m, src)
}
func (m *Keyfile_Key) XXX_Size() int {
	return xxx_messageInfo_Keyfile_Key.Size(m)
}
func (m *Keyfile_Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Keyfile_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Keyfile_Key proto.InternalMessageInfo

func (m *Keyfile_Key) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Keyfile_Key) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Keyfile_Key) GetInit() []byte {
	if m != nil {
		return m.Init
	}
	return nil
}

type Keyfile_Secret struct {
	Secret               []byte   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keyfile_Secret) Reset()         { *m = Keyfile_Secret{} }
func (m *Keyfile_Secret) String() string { return proto.CompactTextString(m) }
func (*Keyfile_Secret) ProtoMessage()    {}
func (*Keyfile_Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_2accf5df6005b7d4, []int{0, 1}
}

func (m *Keyfile_Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keyfile_Secret.Unmarshal(m, b)
}
func (m *Keyfile_Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keyfile_Secret.Marshal(b, m, deterministic)
}
func (m *Keyfile_Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keyfile_Secret.Merge(m, src)
}
func (m *Keyfile_Secret) XXX_Size() int {
	return xxx_messageInfo_Keyfile_Secret.Size(m)
}
func (m *Keyfile_Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Keyfile_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Keyfile_Secret proto.InternalMessageInfo

func (m *Keyfile_Secret) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func init() {
	proto.RegisterType((*Keyfile)(nil), "keypb.Keyfile")
	proto.RegisterType((*Keyfile_Key)(nil), "keypb.Keyfile.Key")
	proto.RegisterType((*Keyfile_Secret)(nil), "keypb.Keyfile.Secret")
}

func init() { proto.RegisterFile("key.proto", fileDescriptor_2accf5df6005b7d4) }

var fileDescriptor_2accf5df6005b7d4 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4e, 0xad, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4e, 0xad, 0x2c, 0x48, 0x52, 0xda, 0xc8, 0xc8,
	0xc5, 0xee, 0x9d, 0x5a, 0x99, 0x96, 0x99, 0x93, 0x2a, 0x24, 0xc9, 0xc5, 0x91, 0x9d, 0x5a, 0x19,
	0x5f, 0x9c, 0x98, 0x53, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0xc4, 0x9e, 0x9d, 0x5a, 0x19,
	0x9c, 0x98, 0x53, 0x22, 0xa4, 0xc6, 0xc5, 0x92, 0x9d, 0x5a, 0x59, 0x2c, 0xc1, 0xa4, 0xc0, 0xac,
	0xc1, 0x6d, 0x24, 0xa4, 0x07, 0xd6, 0xac, 0x07, 0xd5, 0x08, 0xa2, 0x83, 0xc0, 0xf2, 0x52, 0x8e,
	0x5c, 0xcc, 0xde, 0xa9, 0x95, 0x42, 0x42, 0x5c, 0x2c, 0xc5, 0x39, 0xa5, 0xe9, 0x60, 0x53, 0x38,
	0x83, 0xc0, 0x6c, 0x90, 0x58, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0x13, 0xd8, 0x64, 0x30, 0x1b, 0x24,
	0x96, 0x99, 0x97, 0x59, 0x22, 0xc1, 0x0c, 0x11, 0x03, 0xb1, 0xa5, 0x14, 0xb8, 0xd8, 0x82, 0x53,
	0x93, 0x8b, 0x52, 0x4b, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0xc1, 0x2c, 0xa8, 0x6b, 0xa0, 0xbc, 0x24,
	0x36, 0xb0, 0x0f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xfe, 0x02, 0xf9, 0xce, 0x00,
	0x00, 0x00,
}
