// Code generated by protoc-gen-go. DO NOT EDIT.
// source: key.proto

package keypb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Keyfile is the storage format for a key file. The keys in a file are
// encrypted with AES-256 using a key derived from a passphrase using scrypt.
type Keyfile struct {
	Keys                 []*Keyfile_Key `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Keyfile) Reset()         { *m = Keyfile{} }
func (m *Keyfile) String() string { return proto.CompactTextString(m) }
func (*Keyfile) ProtoMessage()    {}
func (*Keyfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2accf5df6005b7d4, []int{0}
}

func (m *Keyfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keyfile.Unmarshal(m, b)
}
func (m *Keyfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keyfile.Marshal(b, m, deterministic)
}
func (m *Keyfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keyfile.Merge(m, src)
}
func (m *Keyfile) XXX_Size() int {
	return xxx_messageInfo_Keyfile.Size(m)
}
func (m *Keyfile) XXX_DiscardUnknown() {
	xxx_messageInfo_Keyfile.DiscardUnknown(m)
}

var xxx_messageInfo_Keyfile proto.InternalMessageInfo

func (m *Keyfile) GetKeys() []*Keyfile_Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

// A Key is stored as an array of bytes that has been encrypted in CTR
// mode. Each key has a slug that can be used to choose which key to decrypt.
// Since key secrets are expected to be both short and random, they are not
// compressed before storage.
type Keyfile_Key struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Init                 []byte   `protobuf:"bytes,3,opt,name=init,proto3" json:"init,omitempty"`
	Salt                 []byte   `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keyfile_Key) Reset()         { *m = Keyfile_Key{} }
func (m *Keyfile_Key) String() string { return proto.CompactTextString(m) }
func (*Keyfile_Key) ProtoMessage()    {}
func (*Keyfile_Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_2accf5df6005b7d4, []int{0, 0}
}

func (m *Keyfile_Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keyfile_Key.Unmarshal(m, b)
}
func (m *Keyfile_Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keyfile_Key.Marshal(b, m, deterministic)
}
func (m *Keyfile_Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keyfile_Key.Merge(m, src)
}
func (m *Keyfile_Key) XXX_Size() int {
	return xxx_messageInfo_Keyfile_Key.Size(m)
}
func (m *Keyfile_Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Keyfile_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Keyfile_Key proto.InternalMessageInfo

func (m *Keyfile_Key) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Keyfile_Key) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Keyfile_Key) GetInit() []byte {
	if m != nil {
		return m.Init
	}
	return nil
}

func (m *Keyfile_Key) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func init() {
	proto.RegisterType((*Keyfile)(nil), "keypb.Keyfile")
	proto.RegisterType((*Keyfile_Key)(nil), "keypb.Keyfile.Key")
}

func init() { proto.RegisterFile("key.proto", fileDescriptor_2accf5df6005b7d4) }

var fileDescriptor_2accf5df6005b7d4 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4e, 0xad, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4e, 0xad, 0x2c, 0x48, 0x52, 0xea, 0x60, 0xe4,
	0x62, 0xf7, 0x4e, 0xad, 0x4c, 0xcb, 0xcc, 0x49, 0x15, 0x52, 0xe3, 0x62, 0xc9, 0x4e, 0xad, 0x2c,
	0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd2, 0x03, 0xab, 0xd0, 0x83, 0xca, 0x82, 0xe8,
	0x20, 0xb0, 0xbc, 0x54, 0x28, 0x17, 0xb3, 0x77, 0x6a, 0xa5, 0x90, 0x10, 0x17, 0x4b, 0x71, 0x4e,
	0x69, 0xba, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x0d, 0x12, 0x4b, 0x49, 0x2c, 0x49,
	0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x41, 0x62, 0x99, 0x79, 0x99, 0x25, 0x12,
	0xcc, 0x10, 0x31, 0x10, 0x1b, 0xac, 0x37, 0x31, 0xa7, 0x44, 0x82, 0x05, 0x22, 0x06, 0x62, 0x27,
	0xb1, 0x81, 0x1d, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x00, 0x15, 0xb2, 0xa5, 0x00,
	0x00, 0x00,
}
